name: Sample Run Include Syntax Json Format
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
     - uses: actions/checkout@v3
     - name: Retrieve the commit message  
       id: get_commit_message
       run: echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.sha }})" 
     - name: Extract Jira Ticket name
       id: extract
       run: |
        input_string="${{ steps.get_commit_message.outputs.commit_message }}"
        ticket_jira=$(echo $input_string | sed -n 's/.*\[\([^]]*\)\].*/\1/p')
        echo "::set-output name=ticket_jira::$ticket_jira"
        jobs_names=$(echo $input_string | sed -n 's/\[[^]]*\]\s*\(.*\)/\1/p')
        echo "::set-output name=jobs_names::$jobs_names"
     - name: Set Dynamic Matrix containing job names
       id: setmatrix
       env: 
        message: "${{ steps.extract.outputs.jobs_names }}"
       run: |
           matrixStringifiedObject="{\"include\":["
           IFS=',' read -ra words <<< "$message"
            for word in "${words[@]}"; do
              matrixStringifiedObject+="{\"word\":\"$word\"},"
            done
                 matrixStringifiedObject+="]}"
           echo "::set-output name=matrix::$matrixStringifiedObject"
       shell: bash
    #  - name: Check Jira  
    #    run: echo "${{ steps.extract.outputs.ticket_jira }}"
    #  - name: Get JIRA TICKET
    #    uses: indiesdev/curl@v1.1
    #    id: get_ticket
    #    with:
    #     url: 'https://olive-soft.atlassian.net/rest/api/3/issue/${{ steps.extract.outputs.ticket_jira }}'
    #     method: 'GET'
    #     accept: 200,201,204
    #     basic-auth-token: ${{ secrets.JIRA_TOKEN }}
    #     log-response: true
    #  - name: Get JIRA TICKET
    #    uses: indiesdev/curl@v1.1
    #    id: update_ticket
    #    with:
    #     url: 'https://olive-soft.atlassian.net/rest/api/2/issue/${{ steps.extract.outputs.ticket_jira }}/transitions'
    #     method: 'POST'
    #     accept: 200,201,204
    #     basic-auth-token: ${{ secrets.JIRA_TOKEN }}
    #     log-response: true
    #     body : '{"transition": { "id": "41" } }' 
     - name: test 
        run echo " ${{ steps.setmatrix.outputs.matrix }}"
      
           
         
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.job1.outputs.matrix) }}
    steps:
    - run: echo Run ${{ matrix.word }}
    - run: echo " only the first run  ${{ matrix.word }}"
      if: ${{ matrix[0] == matrix.value }}

    
    
