on: [push]
jobs:
    setup:
        runs-on: ubuntu-latest
        outputs:
          message: "${{ steps.get_commit_message.outputs.commit_message }}"
        steps:
        - uses: actions/checkout@v3
        - name: Set timezone
          run: sudo timedatectl set-timezone Europe/London
        - name: Get current date in Europe/London timezone
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        - name: Get London Time
          id: london_time
          run: |
            echo "::set-output name=london_time::$(date -d '+2 minutes' '+%H:%M')"
          shell: bash
          env:
            TZ: Europe/London
        - name: Récupérer le message de commit
          id: get_commit_message
          run: echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.sha }})"  
      
    build:
        needs: [ setup ]
        runs-on: ubuntu-latest
        strategy:
          matrix:
            value: ${{ needs.setup.outputs.message }}
        steps:
        - name: Get London Time 
          run: echo "${{ matrix.value }}"

        
        
        
       
