on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.split.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Récupérer le message de commit
        id: get_commit_message
        run: echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.sha }})" 
      - name: split
        run: |
         matrixStringifiedObject="{\"include\":[{\"run\":\"run1\"},{\"run\":\"run2\"}]}"
         echo "::set-output name=matrix::$matrixStringifiedObject"
      
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        element: ${{ fromJson(needs.setup.outputs.message)}}

    steps:
      - name: Get London Time   
        run: ${{ matrix.element }}
