on: [push]

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup matrix combinations
        id: setup-matrix-combinations
        env:
            message: "a,b"
        run: |
            
             IFS=',' read -ra words <<< "$message"
             MATRIX_PARAMS_COMBINATIONS=''
             for word in "${words[@]}"; do
              MATRIX_PARAMS_COMBINATIONS+="{word: $word}"$'\n'
             done
             echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}
  matrix-job:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}
    steps:
      - run: |
          echo word=${{ matrix.word }}
      
