on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Split string
      id: split
      uses: rishabhgupta/split-by@v1
      with:
        string: 'Hello,world'
        split-by: ','
    outputs:
      my_matrix: ${{ toJson(steps.split.outputs.result) }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        element: ${{ fromJson(needs.setup.outputs.my_matrix) }}
    steps:
    - name: Print element
      run: echo ${{ matrix.element }}
