on: [push]

jobs:
    job1:
      runs-on: ubuntu-latest
      outputs:
        my-array: ${{ steps.step1.outputs.my-JSON_STRING}}
      steps:
        - name: Step 1
          id: step1
          
          run: |
            myArray=("cat" "dog" "mouse" "frog")
            echo "::set-output name=JSON_STRING=$( jq -n \
                  --arg el "$my_array" \
                  '{elements: $el}' )

    job2:
      needs: [job1]
      runs-on: ubuntu-latest
      strategy:
        matrix:
          my_element: ${{ fromJson(needs.job1.outputs.my-array).elements }}
      steps:
        - name: Step 2
          run: |
            my_element="${{ matrix.my_element }}"
            echo "My element is $my_element"
