name: Sample Run Include Syntax Json Format
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
     - uses: actions/checkout@v3
     - name: Récupérer le message de commit
       id: get_commit_message
       run: echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.sha }})" 
     - name: Generate output string
       run: |
         input_string ="[tal123] job 1 job2"
          # extract substring in brackets
          $substring = $input_string -replace '[^\[\]]*\[([^\[\]]*)\].*', '$1'
          # extract text outside of brackets
          $other_text = $input_string -replace '\[([^\[\]]*)\]', ''
          # set output variables
          Write-Output "::set-output name=substring::$substring"
          Write-Output "::set-output name=other_text::$other_text"
     - name: Print Outputs
       run: |
          echo "Substring: ${{ steps.extract.outputs.substring }}"
          echo "Other Text: ${{ steps.extract.outputs.other_text }}"
