name: TMC

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Artifacts from Commit message
      uses: fjogeleit/http-request-action@v1
      id: artifacts
      with:
        url: 'https://api.eu.cloud.talend.com/tmc/v2.6/artifacts'
        method: 'GET'
        bearerToken: ${{ secrets.TMC_TOKEN }}
        customHeaders: '{"Content-Type": "application/json"}'
